### Hello World

GET http://localhost:7777/

### CREATE Polls

POST http://localhost:7777/poll
Content-Type: application/json

{
  "title": "Melhores ferramentas Javascript",
  "options": ["ReactJS", "NodeJS", "Vite", "Heroku", "Fastify"]
}

### GET Poll

GET http://localhost:7777/poll/clsgunfxe0000rk52fmxgshea

### GET All Polls

GET http://localhost:7777/allpolls

### POST Vote on Poll

POST http://localhost:7777/poll/clsgunfxe0000rk52fmxgshea/votes
Content-Type: application/json

{
  "pollOptionId": "clsgunfxi0003rk521g7wo6lf"
}

