### Hello World

GET http://localhost:7777/

### CREATE Polls

POST http://localhost:7777/poll
Content-Type: application/json

{
  "title": "testando a enquete 3",
  "options": ["ReactJS", "NodeJS", "Vite"]
}

### GET Polls

GET http://localhost:7777/poll/clsepw69100001vbo283dgslv

### GET Polls

GET http://localhost:7777/allpolls